export default {
  products: [
    {
      _id: "1",
      name: "Mens Solid Slim Fit Casual Shirt with Spread Collar and Long",
      image: "/images/product-1.jpg",
      price: 599,
      brand: "cobb",
      rating: 4,
      numReviews: 10,
      countInStock: 4,
    },
    {
      _id: "2",
      name: "Symbol Premium Men's All Day Fresh Buttondown Oxford Shirt (Regular Fit)",
      image: "/images/product-2.jpg",
      price: 700,
      brand: "Symbol Premium",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "3",
      name: "Men Work Regular Fit Utility Pants",
      image: "/images/product-3.jpg",
      price: 1700,
      brand: "Peter England",
      rating: 5,
      numReviews: 10,
      countInStock: 9,
    },
    {
      _id: "4",
      name: "Men's Color Block Oversized Fit Full Sleeve Hooded Terry T-Shirt",
      image: "/images/product-4.webp",
      price: 699,
      brand: "Bewakoof",
      rating: 3.5,
      numReviews: 10,
      countInStock: 9,
    },
    {
      _id: "5",
      name: "Columbia Mens Tech Trail Graphic Tee",
      image: "/images/product-5.webp",
      price: 2500,
      brand: "Columbia",
      rating: 5,
      numReviews: 10,
      countInStock: 8,
    },
    {
      _id: "6",
      name: "Regular Fit Track Pant for Men",
      image: "/images/product-6.jpg",
      price: 700,
      brand: "GRECIILOOKS",
      rating: 2.5,
      numReviews: 10,
      countInStock: 7,
    },
  ],
};
